# Generated by Django 4.1.7 on 2023-02-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Required email', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
