# Generated by Django 4.1.7 on 2023-03-04 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=6, verbose_name='Пол пользователя')),
                ('avatar', models.ImageField(default='default_avatar.svg', upload_to='avatars/', verbose_name='Аватар пользователя')),
                ('bio', models.TextField(blank=True, verbose_name='Информация о пользователе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['user'],
            },
        ),
    ]
