# Generated by Django 4.1.7 on 2023-03-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Required email', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
