# Generated by Django 4.1.7 on 2023-03-02 17:18

import book.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('total_pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ru', 'Russian'), ('ua', 'Ukrainian'), ('pl', 'Polish')], default='en', max_length=30, verbose_name='Язык')),
                ('published_data', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('isbn', models.CharField(max_length=30, validators=[book.validators.validate_isbn], verbose_name='ISBN')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.author', verbose_name='Автор книги')),
                ('genre', models.ManyToManyField(related_name='select_books', to='book.genre')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Опубликовал')),
            ],
            options={
                'ordering': ['author', 'title'],
            },
        ),
    ]
