# Generated by Django 4.1.7 on 2023-03-05 09:23

import book.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='topics',
            field=models.ManyToManyField(related_name='select_books', to='book.topic', verbose_name='Топики'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[(None, 'Choose a language:'), ('en', 'English'), ('de', 'German'), ('ru', 'Russian'), ('ua', 'Ukrainian'), ('pl', 'Polish')], max_length=25, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=75, validators=[book.validators.validate_topic], verbose_name='Топик'),
        ),
    ]
