# Generated by Django 4.1.7 on 2023-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_genre_book_topics_alter_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='books/', verbose_name='PDF'),
        ),
    ]
