# Generated by Django 4.1.7 on 2023-03-16 18:31

import book.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='topics',
            field=models.ManyToManyField(related_name='select_books', to='book.topic', verbose_name='Топики'),
        ),
    ]
