# Generated by Django 4.1.7 on 2023-03-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(max_length=150, upload_to='books/', verbose_name='PDF'),
        ),
    ]
