# Generated by Django 4.1.7 on 2023-03-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_total_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
    ]
