# Generated by Django 4.1.7 on 2023-03-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_total_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentbook',
            old_name='text',
            new_name='comment',
        ),
    ]
