# Generated by Django 4.1.7 on 2023-03-28 11:10

import book.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_rename_text_commentbook_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[book.validators.validate_isbn], verbose_name='ISBN'),
        ),
    ]
