# Generated by Django 4.1.7 on 2023-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='SLUG'),
        ),
    ]
