# Generated by Django 4.1.7 on 2023-03-07 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[(None, 'Not stated'), ('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Пол пользователя')),
                ('avatar', models.ImageField(default='default_avatar.svg', upload_to='avatars/', verbose_name='Аватар пользователя')),
                ('bio', models.TextField(blank=True, verbose_name='Информация о пользователе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['user'],
            },
        ),
    ]
