# Generated by Django 4.1.7 on 2023-03-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='SLUG'),
        ),
    ]
